engines:
  rubocop:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
    - lib/**/*
exclude_paths:
  - coverage/
  - docs/
  - features/
  - logo/
  - pkg/
  - samples/
  - spec/
  - tmp/
