engines:
  rubocop:
    enabled: true
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 29
ratings:
  paths:
    - lib/**/*
exclude_paths:
  - coverage/
  - docs/
  - features/
  - logo/
  - pkg/
  - samples/
  - spec/
  - tmp/
